version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: local-mongod
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo:/data/mongo
    networks:
      local_net:
        ipv4_address: 192.168.200.2

  redis:
    image: redis:latest
    container_name: local-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis:/data/redis
    networks:
      local_net:
        ipv4_address: 192.168.200.3

  postgresql:
    image: postgres:latest
    container_name: local-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/data/postgres
    networks:
      local_net:
        ipv4_address: 192.168.200.4

networks:
  local_net:
    internal: true
    ipam:
      config:
        - subnet: 192.168.200.0/24